version: 2

jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/cypress-brown-bag
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-node-{{ arch }}-{{ .Branch }}-
            - v2-node-{{ arch }}-
      - run: npm i
      - save_cache:
          key: v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/cypress-brown-bag/node_modules
            - ~/.cache
      - run: npm run cypress
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
